services:
  app_proxy:
    environment:
      APP_HOST: lampas-lampac_server_1
      APP_PORT: 9118

  server:
    image: immisterio/lampac:latest
    # user: "1000:1000"
    restart: "on-failure"
    stop_grace_period: "1m"
    init: true
    volumes:
      - ./${APP_DATA_DIR}/data/config.json:/home/init.conf
      - ./${APP_DATA_DIR}/data/personal.json:/home/wwwroot/lampa-main/personal.lampa:ro
